version: '3.8'

services:
  web:
    image: ghcr.io/${GITHUB_USER}/bixengine-${CLIENT_ID}:latest
    restart: always
    env_file:
      - .env
    networks:
      - bix-network
    volumes:
      - ./uploads:/app/uploads
      - ./xml:/app/xml
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 bixengine.wsgi:application

  qcluster:
    image: ghcr.io/${GITHUB_USER}/bixengine-${CLIENT_ID}:latest
    restart: always
    env_file:
      - .env
    networks:
      - bix-network
    volumes:
      - ./uploads:/app/uploads
      - ./xml:/app/xml
    command: python manage.py qcluster

networks:
  bix-network:
    external: true