version: '3.8'

services:
  web:
    # L'immagine viene scaricata dal registro privato di GitHub
    image: ghcr.io/${GITHUB_USER}/${IMAGE_BASE}-${CLIENT_ID}:latest
    restart: always
    env_file:
      - .env
    volumes:
      # Mappiamo solo le cartelle dei dati persistenti
      - ./uploads:/app/uploads
      - ./xml:/app/xml
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 bixengine.wsgi:application

  qcluster:
    image: ghcr.io/${GITHUB_USER}/${IMAGE_BASE}-${CLIENT_ID}:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./xml:/app/xml
    command: python manage.py qcluster